#!/bin/sh

[[ ! -d "/Library/Application Support/Macromedia" ]] && mkdir -p "/Library/Application Support/Macromedia"

if [ ! -f "/Library/Application Support/Macromedia/mms.cfg" ]; then
	touch "/Library/Application Support/Macromedia/mms.cfg"
	echo "AutoUpdateDisable=0" >> "/Library/Application Support/Macromedia/mms.cfg"
	echo "SilentAutoUpdateEnable=1" >> "/Library/Application Support/Macromedia/mms.cfg"

else
	sed -i'' -e 's/^\(AutoUpdateDisable=\).*/\10/' /Library/Application\ Support/Macromedia/mms.cfg
	sed -i'' -e 's/^\(SilentAutoUpdateEnable=\).*/\11/' /Library/Application\ Support/Macromedia/mms.cfg

fi

exit 0